/**
 * INTENÇÃO — reconhecimento COMPOSICIONAL, não catálogo fechado.
 */
export type Intent="REQUEST_SOLUTION"|"REQUEST_ORGANIZATION"|"REQUEST_LISTENING"|"POLICY_FAILURE"|"CLOSE"|"CONTINUE";
export type IntentFeature="desiderative"|"imperative_speech"|"request_verb"|"interrogative"|"deontic"|"solution_object"|"listening_object"|"organization_object"|"negated_help"|"negated_understanding"|"explicit_prior_request"|"terminative"|"temporal_deferral"|"brevity_demand"|"contrast"|"hedging"|"high_density";
export type IntentReading={primary:Intent;distribution:Record<Intent,number>;features:IntentFeature[];confidence:number};
const L="(?<![\\wÀ-ÿ])",R="(?![\\wÀ-ÿ])";
const DESIDERATIVE=/\b(quer(o|ia|endo)?|precis(o|ava|ando|o de)|gostaria|to precisando|t(ô|o) precisando|me falta|faltou|carec(o|endo))\b/i;
const SPEECH_VERB=new RegExp(L+"(d(á|a|ê|e)|diz|diga|fal(a|e)|most(ra|re)|indic(a|e)|sugir(a|e)|sugere|apont(a|e)|respond(a|e)|explic(a|e)|ajud(a|e)|resolv(a|e)|manda|passa|solta|traz)"+R,"i");
const REQUEST_VERB=new RegExp(L+"(ped(i|ir|indo|iu)|solicit(o|ei|ar)|pergunt(o|ei|ar|ando)|indag(o|uei)|questionei)"+R,"i");
const INTERROGATIVE=new RegExp("\\?|"+L+"(o que|que|qual|quais|como|por que|porqu(e|ê)|quando|onde|quem|cad(ê|e)|ser(á|a) que)"+R,"i");
const DEONTIC=/\b(dev(o|eria|emos)|tenho que|preciso fazer|(é|e) pra eu|melhor eu)\b/i;
const SOLUTION_STEM=/\b\w*(soluç|solu(c|ç)(ã|a)o|suges|conselh|opini|ideia|ideias|caminh|sa(í|i)d|alternativ|respost|orienta|dica|recomenda|plan(o|os)|passo a passo|dire(ç|c)(ã|a)o|norte|jeito de|forma de|maneira de)\w*\b/i;
const ACTION_QUERY=/\b(o que (eu )?(fa(ç|c)o|fa(ç|c)a|devo|dever(ia|íamos)|posso)|o que voc(ê|e) (faria|acha que|sugere|recomenda)|como (eu )?(fa(ç|c)o|resolv|sai|come(ç|c)|melhor|lido|trato|encaro)\w*|por onde (eu )?come(ç|c)\w*|qual (o )?(caminho|primeiro passo|pr(ó|o)ximo passo))\b/i;
const LISTENING_OBJECT=/\b(s(ó|o) (quero|queria|precisava|preciso) (falar|desabafar|conversar|botar pra fora|colocar pra fora)|(quero|queria|preciso) (desabafar|ser ouvid[oa]|falar um pouco)|n(ã|a)o (quero|preciso de) (conselho|solu(ç|c)(ã|a)o|dica|resposta)|s(ó|o) me (escuta|ouve|escute|ou(ç|c)a))\b/i;
const ORGANIZATION_OBJECT=/\b(organiz\w*|clarear|clareza|separar|estruturar|entender melhor|p(ô|o)r ordem|botar ordem|resumir|sintetizar|listar|mapear)\b/i;
export const NEGATED_HELP=/\b(n(ã|a)o|nada|nem um pouco|pouco)\b[^.?!]{0,18}\b(ajud|serv(iu|e)|resolv(eu|e)|adiant(ou|a)|acrescent(ou|a)|contribu)\w*/i;
const NEGATED_UNDERSTANDING=/\b(voc(ê|e) n(ã|a)o (entendeu|captou|pegou|compreendeu)|n(ã|a)o (é|e|foi) (isso|bem isso|o que|nada disso)|n(ã|a)o era isso|(t(á|a)|est(á|a)) (errado|equivocado)|nada a ver|passou longe|voc(ê|e) (est(á|a) )?(s(ó|o) )?repetindo|de novo a mesma (coisa|resposta))\b/i;
const EXPLICIT_PRIOR_REQUEST=/\b(eu (j(á|a) )?(pedi|perguntei|falei|disse)|(j(á|a)|acabei de) (pedir|perguntar|falar|dizer)|(é|e) o que eu (pedi|perguntei))\b/i;
const TERMINATIVE=/\b(chega|basta|parar?|paro|encerr\w*|termin(ar|amos|o)|fechad[oa]|(é|e) isso|(t|est)(á|a) (bom|(ó|o)timo) (ent(ã|a)o|assim)|deixa (pra|para) l(á|a)|vou (dormir|nessa|indo|embora)|tchau|falou|at(é|e) (mais|logo|amanh(ã|a)|a pr(ó|o)xima))\b/i;
const TEMPORAL_DEFERRAL=/\b(por (hoje|agora|enquanto)|depois (eu|a gente|voltamos|continu\w*)|amanh(ã|a) (eu|a gente|continu\w*)|outra hora|noutro dia|mais tarde|fica (pra|para) (depois|amanh(ã|a)))\b/i;
const BREVITY_DEMAND=/\b(seja (objetiv|diret|breve)\w*|vai direto|sem rodeio|resumid[oa]|curto e grosso|direto ao ponto|sem enrola(ç|c)(ã|a)o|responde logo)\b/i;
const CONTRAST=/\b(mas|por(é|e)m|s(ó|o) que|ao mesmo tempo|por outro lado|entretanto|embora|apesar)\b/i;
const HEDGING=new RegExp(L+"(acho|talvez|n(ã|a)o sei|parece|pode ser|ser(á|a)|meio que|sei l(á|a))"+R,"i");
export function extractIntentFeatures(input:string):IntentFeature[]{const t=input.trim(),words=t.split(/\s+/).filter(Boolean).length,f:IntentFeature[]=[];if(DESIDERATIVE.test(t))f.push("desiderative");if(SPEECH_VERB.test(t))f.push("imperative_speech");if(REQUEST_VERB.test(t))f.push("request_verb");if(INTERROGATIVE.test(t))f.push("interrogative");if(DEONTIC.test(t))f.push("deontic");if(SOLUTION_STEM.test(t)||ACTION_QUERY.test(t))f.push("solution_object");if(LISTENING_OBJECT.test(t))f.push("listening_object");if(ORGANIZATION_OBJECT.test(t))f.push("organization_object");if(NEGATED_HELP.test(t))f.push("negated_help");if(NEGATED_UNDERSTANDING.test(t))f.push("negated_understanding");if(EXPLICIT_PRIOR_REQUEST.test(t))f.push("explicit_prior_request");if(TERMINATIVE.test(t))f.push("terminative");if(TEMPORAL_DEFERRAL.test(t))f.push("temporal_deferral");if(BREVITY_DEMAND.test(t))f.push("brevity_demand");if(CONTRAST.test(t))f.push("contrast");if(HEDGING.test(t))f.push("hedging");if(words>=60)f.push("high_density");return f;}
const ZERO:Record<Intent,number>={REQUEST_SOLUTION:0,REQUEST_ORGANIZATION:0,REQUEST_LISTENING:0,POLICY_FAILURE:0,CLOSE:0,CONTINUE:0.6};
export function readIntent(input:string):IntentReading{const features=extractIntentFeatures(input),has=(x:IntentFeature)=>features.includes(x),d={...ZERO};if(has("solution_object")){if(has("desiderative"))d.REQUEST_SOLUTION+=1.5;if(has("interrogative"))d.REQUEST_SOLUTION+=1.3;if(has("imperative_speech"))d.REQUEST_SOLUTION+=1.3;if(has("deontic"))d.REQUEST_SOLUTION+=.9;if(has("request_verb"))d.REQUEST_SOLUTION+=1.2;if(has("negated_help"))d.REQUEST_SOLUTION+=.8;d.REQUEST_SOLUTION+=.55;}if(has("imperative_speech")&&!has("solution_object"))d.REQUEST_SOLUTION+=.95;if(has("brevity_demand"))d.REQUEST_SOLUTION+=1.3;if(has("negated_understanding"))d.POLICY_FAILURE+=1.6;if(has("negated_help"))d.POLICY_FAILURE+=1.4;if(has("explicit_prior_request"))d.POLICY_FAILURE+=1.2;if(has("terminative"))d.CLOSE+=1.4;if(has("temporal_deferral"))d.CLOSE+=1.1;if(has("terminative")&&has("temporal_deferral"))d.CLOSE+=.7;if(d.REQUEST_SOLUTION>1.2)d.CLOSE-=1.2;if(has("listening_object")){d.REQUEST_LISTENING+=2;d.REQUEST_SOLUTION-=1.6;}if(has("high_density")&&!has("solution_object"))d.REQUEST_LISTENING+=.8;if(has("organization_object"))d.REQUEST_ORGANIZATION+=1.2;if(has("contrast"))d.REQUEST_ORGANIZATION+=.5;(Object.keys(d) as Intent[]).forEach(k=>{d[k]=Math.max(0,d[k]);});const entries=(Object.keys(d) as Intent[]).map(k=>[k,d[k]] as const).sort((a,b)=>b[1]-a[1]),[top,topScore]=entries[0],second=entries[1][1],confidence=Math.max(.15,Math.min(.95,(topScore-second)/2+(has("hedging")?-.08:0)+.35));return{primary:top,distribution:d,features,confidence};}
export function requestsAnswer(input:string){const r=readIntent(input);return r.distribution.REQUEST_SOLUTION>=1.2||r.primary==="REQUEST_SOLUTION";}
export function signalsPolicyFailure(input:string){return readIntent(input).distribution.POLICY_FAILURE>=1.2;}
export function signalsClosing(input:string){const r=readIntent(input);return r.primary==="CLOSE"&&r.distribution.CLOSE>=1.1;}
export function requestsListeningOnly(input:string){return readIntent(input).distribution.REQUEST_LISTENING>=2;}
