/**
 * MOTOR MESTRE — o ciclo do projeto, explícito no código:
 * observação -> hipótese -> intervenção -> observação da reação -> atualização -> nova decisão
 */
import { GoogleGenAI } from "@google/genai";
import { choosePacing } from "./pacing";
import { extractSignals } from "./signals";
import { readIntent, requestsListeningOnly } from "./intent";
import { readAffect, probableNeed } from "./affect";
import { buildEpistemicMemory, buildTopicGraph } from "./memory";
import { applyUserCorrection, applyUserConfirmation, createHypothesis, updateBelief, describeHypotheses, activeHypotheses, invalidHypotheses, type Hypothesis } from "./hypothesis";
import { decidePolicy, type PolicyAction, type PolicyPenalties } from "./policy";
import { planIntervention } from "./planner";
import { qualityGate, type QualityFailure } from "./quality";
import { buildPrompt, revisionFor, fallbackReply, SAFETY_REPLY } from "./response";
import { defaultLearningStore, biasVector, outcomeFromReaction, type LearningStore, type LearningContext } from "./learning/aggregate";
import { emptyState, readImplicitReaction, inferInterventionResult, updateUncertainty, deriveObjective, type TalkState } from "./state";
import { readCorrection, type CorrectionKind } from "./correction";
import { mesoPenalty, combineScales, type AdaptivityBreakdown } from "./adaptivity";
import type { SpiralEngineOutput, SpiralStructure, ConversationState } from "./types";
type Msg={role:"user"|"assistant";content:string};
const MAX_HISTORY=12,MAX_ATTEMPTS=3,ALL_ACTIONS:PolicyAction[]=["listen","reflect","organize","answer","confront_gently","ask","pivot","close"];
const round1=(ms:number)=>Math.round(ms*10)/10;
export type MasterTrace={attempts:number;failures:QualityFailure[][];penalties:PolicyPenalties;learnedBias:Record<string,number>;finalAction:PolicyAction;usedFallback:boolean;supersededMemories:number;hypothesesActive:number;hypothesesInvalid:number;replanned:boolean;correctionKind:CorrectionKind;adaptivity:AdaptivityBreakdown;uncertainty:number;objective:TalkState["currentObjective"];llmCallCount:number;timing:{preprocessing_ms:number;generation_ms:number;total_ms:number}};
export type MasterResult=SpiralEngineOutput&{state:TalkState;trace:MasterTrace};
const CONFIRMATION=/\b(isso|(é|e) isso|exatamente|exato|(é|e) bem isso|voc(ê|e) entendeu|acertou|(é|e) verdade|isso mesmo)\b/i;
const SAFETY=/\b(vou me matar|quero me matar|vou tirar minha vida|me matar hoje|suicid|me ferir|me machucar|n(ã|a)o quero mais viver|acabar com tudo)\b/i;
function emptyStructure(input:string):SpiralStructure{return{central_question:input.slice(0,220),declared_factors:[],constraints:[],alternatives:[],decision_state:"none",declared_decision:null,open_questions:[],declared_changes:[],memory_candidates:[],confidence:.05};}
export function reconstructState(history:Msg[]):TalkState{const s=emptyState(),users=history.filter(m=>m.role==="user");s.turn=users.length;if(!users.length)return s;const last=users[users.length-1],idx=history.lastIndexOf(last);s.previousState=choosePacing({history:history.slice(0,idx),input:last.content}).state;s.currentState=s.previousState;s.topics=buildTopicGraph(history.slice(0,idx),last.content).nodes.map(n=>n.topic);s.questionsAsked=history.filter(m=>m.role==="assistant").reduce((n,m)=>n+(m.content.match(/\?/g)||[]).length,0);return s;}
function hypothesesFromTurn(prev:Hypothesis[],topics:string[],need:string,turn:number):Hypothesis[]{let store=prev.slice();const ensure=(id:string,kind:Parameters<typeof createHypothesis>[1],claim:string)=>{const found=store.find(h=>h.id===id);if(found){if(found.status!=="REJECTED"&&found.status!=="SUPERSEDED")store=store.map(h=>h.id===id?updateBelief(h,.55,"tema reaparece no relato",turn):h);return;}store.push(updateBelief(createHypothesis(id,kind,claim,turn),.5,"declarado neste turno",turn));};topics.slice(0,4).forEach(t=>ensure("topic:"+t,"topic","o tema "+t+" está em foco"));if(need!=="indefinido")ensure("need:"+need,"need","a necessidade provável é "+need);return store.slice(-24);}
export async function runMasterTurn(args:{history:Msg[];input:string;state?:TalkState|null;learning?:LearningStore}):Promise<MasterResult>{const t0=performance.now(),history=args.history.slice(-MAX_HISTORY),input=args.input,learning=args.learning??defaultLearningStore,prior=args.state??reconstructState(history),turn=prior.turn+1;
const pacing=choosePacing({history,input}),signals=extractSignals(input,pacing.act),intent=readIntent(input),affect=readAffect(input,history.filter(m=>m.role==="user").map(m=>m.content)),graph=buildTopicGraph(history,input),topics=graph.nodes.map(n=>n.topic),emerging=topics.filter(t=>!prior.topics.includes(t));
const lastAssistant=history.filter(m=>m.role==="assistant").slice(-1)[0]?.content??"",correction=readCorrection(input,lastAssistant.split(/\s+/).filter(Boolean).length);
const explicitReaction:TalkState["explicitReaction"]=correction.kind==="INTERVENTION_REJECTION"||correction.kind==="HYPOTHESIS_REJECTION"?"correction":intent.primary==="CLOSE"?"closing":intent.features.includes("explicit_prior_request")?"request_repeat":CONFIRMATION.test(input)&&input.trim().split(/\s+/).length<=8?"confirmation":"none";
const implicitReaction=readImplicitReaction(history,input,prior.topics,topics),resultReading=prior.lastIntervention?inferInterventionResult(explicitReaction,implicitReaction):{result:"unknown" as const,confidence:.2},lastResult=resultReading.result;
if(prior.lastIntervention){const ctx:LearningContext={intent:prior.intent,state:prior.previousState??prior.currentState};learning.record(ctx,prior.lastIntervention,outcomeFromReaction({policyFailure:explicitReaction==="correction",closed:explicitReaction==="closing",continued:implicitReaction==="lengthened"||explicitReaction==="confirmation",repeatedRequest:explicitReaction==="request_repeat"}));}
let hypotheses=hypothesesFromTurn(prior.hypotheses,topics,probableNeed(affect),turn);const invalidBefore=invalidHypotheses(hypotheses).length;if(correction.kind==="INTERVENTION_REJECTION")hypotheses=applyUserCorrection(hypotheses,input,turn,"policy_failure");else if(correction.kind==="HYPOTHESIS_REJECTION"||correction.kind==="FACTUAL_CORRECTION")hypotheses=applyUserCorrection(hypotheses,input,turn,"content");if(explicitReaction==="confirmation")hypotheses=applyUserConfirmation(hypotheses,turn);const invalidated=invalidHypotheses(hypotheses).length-invalidBefore;
const need=requestsListeningOnly(input)?"escuta":probableNeed(affect),closureState:TalkState["closureState"]=prior.closureState==="closed"?"closed":intent.primary==="CLOSE"?"closing":prior.closureState==="closing"?"closed":prior.turn>=3&&intent.primary==="REQUEST_SOLUTION"?"converging":prior.closureState;
const rejectedStrategies=lastResult==="rejected"&&resultReading.confidence>=.6&&prior.lastIntervention?Array.from(new Set([...prior.rejectedStrategies,prior.lastIntervention])):prior.rejectedStrategies;
const state:TalkState={turn,topics,emergingTopics:emerging,intent:intent.primary,intentConfidence:intent.confidence,intentFeatures:intent.features,need,affect,hypotheses,lastIntervention:prior.lastIntervention,lastInterventionResult:lastResult,explicitReaction,implicitReaction,previousState:prior.currentState,currentState:pacing.state,nextStrategy:null,needsReplan:lastResult==="rejected"&&resultReading.confidence>=.6,rejectedStrategies,questionsAsked:prior.questionsAsked,interventionHistory:prior.lastIntervention?[...prior.interventionHistory,{turn:prior.turn,action:prior.lastIntervention,result:lastResult}].slice(-10):prior.interventionHistory,acceptedInterventions:lastResult==="accepted"&&prior.lastIntervention?Array.from(new Set([...prior.acceptedInterventions,prior.lastIntervention])):prior.acceptedInterventions,corrections:correction.kind==="NONE"?prior.corrections:[...prior.corrections,{turn,kind:correction.kind,negated:correction.negated}].slice(-10),sessionEffectiveness:prior.lastIntervention?{...prior.sessionEffectiveness,[prior.lastIntervention]:{tried:(prior.sessionEffectiveness[prior.lastIntervention]?.tried??0)+1,rejected:(prior.sessionEffectiveness[prior.lastIntervention]?.rejected??0)+(lastResult==="rejected"?1:0),accepted:(prior.sessionEffectiveness[prior.lastIntervention]?.accepted??0)+(lastResult==="accepted"?1:0)}}:prior.sessionEffectiveness,currentObjective:deriveObjective(intent.primary,need,closureState),closureState,safetyState:"normal",uncertainty:updateUncertainty(prior.uncertainty,{correctionKind:correction.kind,resultConfidence:resultReading.confidence,affectConfidence:affect.overallConfidence})};
if(SAFETY.test(input)){const ts=performance.now(),trace:MasterTrace={attempts:0,failures:[],penalties:{},learnedBias:{},finalAction:"listen",usedFallback:false,supersededMemories:invalidated,hypothesesActive:activeHypotheses(hypotheses).length,hypothesesInvalid:invalidHypotheses(hypotheses).length,replanned:false,correctionKind:correction.kind,adaptivity:{},uncertainty:state.uncertainty,objective:"compreender",llmCallCount:0,timing:{preprocessing_ms:round1(ts-t0),generation_ms:0,total_ms:round1(ts-t0)}};return{reply:SAFETY_REPLY,structure:emptyStructure(input),safety_state:"risk_detected",conversation_state:"holding",state:{...state,currentState:"holding",lastIntervention:"listen",safetyState:"risk_detected"},trace};}
const ctx:LearningContext={intent:intent.primary,state:pacing.state},learned=biasVector(learning,ctx,ALL_ACTIONS),meso:Partial<Record<PolicyAction,number>>={};ALL_ACTIONS.forEach(a=>{const p=mesoPenalty(state.sessionEffectiveness,a);if(p)meso[a]=p;});if(state.needsReplan&&prior.lastIntervention)meso[prior.lastIntervention]=(meso[prior.lastIntervention]||0)+5;rejectedStrategies.forEach(a=>{meso[a]=(meso[a]||0)+4;});const {penalties:basePenalties,breakdown}=combineScales({micro:{},meso,macro:learned});const plan=planIntervention(signals,pacing.state,history,prior.currentState);let policy=decidePolicy(signals,pacing.state,history,plan.userModel,basePenalties);const answerFirst=intent.primary==="REQUEST_SOLUTION"||policy.answerFirst,listeningOnly=need==="escuta"&&requestsListeningOnly(input),tPre=performance.now();const trace:MasterTrace={attempts:0,failures:[],penalties:basePenalties,learnedBias:learned,finalAction:policy.primary,usedFallback:false,supersededMemories:invalidated,hypothesesActive:activeHypotheses(hypotheses).length,hypothesesInvalid:invalidHypotheses(hypotheses).length,replanned:false,correctionKind:correction.kind,adaptivity:breakdown,uncertainty:state.uncertainty,objective:state.currentObjective,llmCallCount:0,timing:{preprocessing_ms:round1(tPre-t0),generation_ms:0,total_ms:0}};
if(listeningOnly){policy={...policy,primary:"listen",answerFirst:false,allowQuestion:false};trace.finalAction="listen";}else if(answerFirst&&policy.primary!=="close"){policy={...policy,primary:"answer",answerFirst:true,allowQuestion:false};trace.finalAction="answer";}
const finish=(reply:string,structure:SpiralStructure,safety:"normal"|"risk_detected",cstate:ConversationState):MasterResult=>{const end=performance.now();trace.timing.generation_ms=round1(end-tPre);trace.timing.total_ms=round1(end-t0);return{reply,structure,safety_state:safety,conversation_state:cstate,state:{...state,nextStrategy:policy.primary,lastIntervention:policy.primary,questionsAsked:state.questionsAsked+(reply.match(/\?/g)||[]).length},trace};};
const useFallback=()=>{trace.usedFallback=true;return finish(fallbackReply({input,history,action:policy.primary,answerFirst:policy.answerFirst,state:pacing.state,need,ambivalent:affect.ambivalent}),emptyStructure(input),"normal",pacing.state);};if(!process.env.GEMINI_API_KEY)return useFallback();
const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY}),contents=[...history,{role:"user" as const,content:input}].map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]})),memory=buildEpistemicMemory(history,input,"turn-"+turn);let penalties:PolicyPenalties={...basePenalties},revision=state.needsReplan?"A intervenção anterior foi rejeitada pelo usuário. NÃO repita a mesma função com outras palavras.":"";
for(let attempt=0;attempt<MAX_ATTEMPTS;attempt++){trace.attempts=attempt+1;try{trace.llmCallCount+=1;const r=await ai.models.generateContent({model:"gemini-2.5-flash",config:{systemInstruction:buildPrompt({state,action:policy.primary,allowQuestion:policy.allowQuestion,questionBudget:policy.questionBudget,answerFirst:policy.answerFirst,rationale:policy.rationale+" | memória="+JSON.stringify(memory).slice(0,800),hypotheses:describeHypotheses(hypotheses),topicGraph:JSON.stringify(graph),revision}),responseMimeType:"application/json",abortSignal:AbortSignal.timeout(15000)},contents});const parsed=JSON.parse(r.text||"{}"),reply=String(parsed?.reply||"").trim(),gate=qualityGate(reply,history,policy.allowQuestion,explicitReaction==="correction",policy.answerFirst);if(gate.ok){const structure=parsed.structure&&typeof parsed.structure==="object"?parsed.structure:emptyStructure(input);if(structure.decision_state!=="decision")structure.declared_decision=null;const valid=["holding","mirroring","deepening","juxtaposing","pivoting","closing"];const cstate:ConversationState=valid.includes(parsed.conversation_state)?parsed.conversation_state:pacing.state;return finish(reply,structure,parsed.safety_state==="risk_detected"?"risk_detected":"normal",cstate);}trace.failures.push(gate.failures);trace.replanned=true;const before=policy.primary;penalties={...penalties};penalties[before]=(penalties[before]||0)+6;if(gate.failures.includes("ANSWER_MISSING")){penalties.listen=(penalties.listen||0)+8;penalties.reflect=(penalties.reflect||0)+8;penalties.ask=(penalties.ask||0)+12;}if(gate.failures.includes("QUESTION_OVERLOAD"))penalties.ask=(penalties.ask||0)+12;policy=decidePolicy(signals,pacing.state,history,plan.userModel,penalties);if(answerFirst)policy={...policy,primary:"answer",answerFirst:true,allowQuestion:false};trace.penalties=penalties;trace.finalAction=policy.primary;revision=revisionFor(gate.failures);}catch{revision="A tentativa anterior falhou tecnicamente. Produza JSON válido e uma resposta útil.";}}
return useFallback();}
