/** ESTADO DA CONVERSA — unidade fundamental do motor. */
import type { ConversationState } from "./types";
import type { Intent, IntentFeature } from "./intent";
import type { AffectState } from "./affect";
import type { Hypothesis } from "./hypothesis";
import type { PolicyAction } from "./policy";
import type { CorrectionKind } from "./correction";
import type { SessionEffectiveness } from "./adaptivity";
export type InterventionResult="accepted"|"rejected"|"neutral"|"unknown";
export type TalkState={turn:number;topics:string[];emergingTopics:string[];intent:Intent;intentConfidence:number;intentFeatures:IntentFeature[];need:"escuta"|"solucao"|"organizacao"|"indefinido";affect:AffectState;hypotheses:Hypothesis[];lastIntervention:PolicyAction|null;lastInterventionResult:InterventionResult;explicitReaction:"correction"|"confirmation"|"request_repeat"|"closing"|"none";implicitReaction:"shortened"|"lengthened"|"topic_moved"|"stable";previousState:ConversationState|null;currentState:ConversationState;nextStrategy:PolicyAction|null;needsReplan:boolean;rejectedStrategies:PolicyAction[];questionsAsked:number;interventionHistory:{turn:number;action:PolicyAction;result:InterventionResult}[];acceptedInterventions:PolicyAction[];corrections:{turn:number;kind:CorrectionKind;negated:string[]}[];sessionEffectiveness:SessionEffectiveness;currentObjective:"compreender"|"organizar"|"resolver"|"encerrar";closureState:"open"|"converging"|"closing"|"closed";safetyState:"normal"|"risk_detected";uncertainty:number};
export function emptyState():TalkState{return{turn:0,topics:[],emergingTopics:[],intent:"CONTINUE",intentConfidence:.3,intentFeatures:[],need:"indefinido",affect:{dimensions:{},ambivalent:false,overallConfidence:.1,statement:"sem leitura"},hypotheses:[],lastIntervention:null,lastInterventionResult:"unknown",explicitReaction:"none",implicitReaction:"stable",previousState:null,currentState:"deepening",nextStrategy:null,needsReplan:false,rejectedStrategies:[],questionsAsked:0,interventionHistory:[],acceptedInterventions:[],corrections:[],sessionEffectiveness:{},currentObjective:"compreender",closureState:"open",safetyState:"normal",uncertainty:.5};}
export function readImplicitReaction(history:{role:"user"|"assistant";content:string}[],input:string,topicsBefore:string[],topicsNow:string[]):TalkState["implicitReaction"]{const users=history.filter(m=>m.role==="user"),prev=users[users.length-1]?.content??"",prevLen=prev.split(/\s+/).filter(Boolean).length,nowLen=input.split(/\s+/).filter(Boolean).length,moved=topicsBefore.length>0&&topicsNow.length>0&&!topicsNow.some(t=>topicsBefore.includes(t));if(moved)return"topic_moved";if(prevLen>=12&&nowLen<=Math.max(3,prevLen*.35))return"shortened";if(prevLen>0&&nowLen>=prevLen*2.2&&nowLen>=25)return"lengthened";return"stable";}
export function inferInterventionResult(explicit:TalkState["explicitReaction"],implicit:TalkState["implicitReaction"]):{result:InterventionResult;confidence:number}{if(explicit==="correction"||explicit==="request_repeat")return{result:"rejected",confidence:.85};if(explicit==="confirmation")return{result:"accepted",confidence:.8};if(explicit==="closing")return{result:"accepted",confidence:.5};if(implicit==="shortened")return{result:"rejected",confidence:.4};if(implicit==="lengthened")return{result:"accepted",confidence:.55};return{result:"neutral",confidence:.3};}
export function updateUncertainty(prev:number,args:{correctionKind:CorrectionKind|"NONE";resultConfidence:number;affectConfidence:number}):number{let u=prev;if(args.correctionKind==="RETRACTION")u+=.2;if(args.correctionKind==="INTERVENTION_REJECTION")u+=.15;if(args.correctionKind==="HYPOTHESIS_REJECTION")u+=.1;if(args.correctionKind==="NONE")u-=.05;u+=(.5-args.resultConfidence)*.2;u-=(args.affectConfidence-.4)*.15;return Math.max(.05,Math.min(.95,Number(u.toFixed(3))));}
export function deriveObjective(intent:string,need:string,closure:TalkState["closureState"]):TalkState["currentObjective"]{if(closure==="closing"||closure==="closed"||intent==="CLOSE")return"encerrar";if(intent==="REQUEST_SOLUTION"||need==="solucao")return"resolver";if(intent==="REQUEST_ORGANIZATION"||need==="organizacao")return"organizar";return"compreender";}
export function serializeState(s:TalkState):string{return JSON.stringify({turn:s.turn,topics:s.topics,intent:s.intent,need:s.need,hypotheses:s.hypotheses,lastIntervention:s.lastIntervention,lastInterventionResult:s.lastInterventionResult,previousState:s.previousState,currentState:s.currentState,rejectedStrategies:s.rejectedStrategies,questionsAsked:s.questionsAsked,interventionHistory:s.interventionHistory.slice(-10),acceptedInterventions:s.acceptedInterventions,corrections:s.corrections.slice(-10),sessionEffectiveness:s.sessionEffectiveness,currentObjective:s.currentObjective,closureState:s.closureState,safetyState:s.safetyState,uncertainty:s.uncertainty});}
export function deserializeState(raw:string|null|undefined):TalkState|null{if(!raw)return null;try{return{...emptyState(),...JSON.parse(raw)} as TalkState;}catch{return null;}}
